# Generated by Django 5.1.1 on 2024-10-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoninfo',
            name='name',
            field=models.CharField(help_text='Obligatorio', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('AMO', 'Andrés Muñoz Órdenes'), ('VAF', 'Verónica Astorga Figueroa'), ('JPC', 'Juan Pérez Cotapos')], max_length=3),
        ),
    ]
